<?php

namespace Database\Seeders;

use App\Models\Fournisseur;
use Illuminate\Database\Seeder;

class FournisseurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fournisseurs = [
            [
                'raison_sociale' => 'Entreprise Construct Maroc SARL',
                'ice' => '001234567890001',
                'if' => 'IF12345678',
                'patente' => 'PA12345678',
                'rc' => 'RC12345',
                'adresse' => 'Rue de la Paix, N° 123, Immeuble Saada',
                'ville' => 'Casablanca',
                'telephone' => '+212660123456',
                'email' => 'contact@construct-maroc.ma',
                'representant' => 'Mohamed Benalou',
                'domaine_activite' => 'Travaux de construction',
                'qualite_representant' => 'Directeur Commercial',
                'cnss' => 'CNSS002345678',
                'banque' => 'Banque Marocaine du Commerce Extérieur',
                'agence_bancaire' => 'Agence Centrale - Casablanca',
                'rib' => '011180000000000001234567',
                'titulaire_compte' => 'Entreprise Construct Maroc SARL',
            ],
            [
                'raison_sociale' => 'Solutions IT Plus EURL',
                'ice' => '002234567890001',
                'if' => 'IF87654321',
                'patente' => 'PA87654321',
                'rc' => 'RC87654',
                'adresse' => 'Avenue Mohammed V, Lot 456, Centre Affaires',
                'ville' => 'Rabat',
                'telephone' => '+212661234567',
                'email' => 'hello@solutionsit.ma',
                'representant' => 'Fatima Azahaf',
                'domaine_activite' => 'Services informatiques',
                'qualite_representant' => 'Responsable Projets',
                'cnss' => 'CNSS003456789',
                'banque' => 'Crédit Agricole Maroc',
                'agence_bancaire' => 'Agence Souissi - Rabat',
                'rib' => '011540000000000002345678',
                'titulaire_compte' => 'Solutions IT Plus EURL',
            ],
            [
                'raison_sociale' => 'Transport Services Logistique SA',
                'ice' => '003234567890001',
                'if' => 'IF11223344',
                'patente' => 'PA11223344',
                'rc' => 'RC11223',
                'adresse' => 'Quartier Industriel, Zone Franche, Boîte 789',
                'ville' => 'Fez',
                'telephone' => '+212662345678',
                'email' => 'logistics@transport-services.ma',
                'representant' => 'Ahmed Karim Bennani',
                'domaine_activite' => 'Transport et logistique',
                'qualite_representant' => 'Gérant',
                'cnss' => 'CNSS004567890',
                'banque' => 'Banque Centrale Populaire',
                'agence_bancaire' => 'Agence Nouvelle Ville - Fez',
                'rib' => '011790000000000003456789',
                'titulaire_compte' => 'Transport Services Logistique SA',
            ],
            [
                'raison_sociale' => 'Fournitures Bureau Import Export LLC',
                'ice' => '004234567890001',
                'if' => 'IF55667788',
                'patente' => 'PA55667788',
                'rc' => 'RC55667',
                'adresse' => 'Boulevard Hassan II, Centre Commercial Reda',
                'ville' => 'Marrakech',
                'telephone' => '+212663456789',
                'email' => 'ventes@fournitures-bureau.ma',
                'representant' => 'Yasmine Chaoui',
                'domaine_activite' => 'Fournitures et équipements',
                'qualite_representant' => 'Directrice des Ventes',
                'cnss' => 'CNSS005678901',
                'banque' => 'Attijaribank',
                'agence_bancaire' => 'Agence Hivernage - Marrakech',
                'rib' => '011930000000000004567890',
                'titulaire_compte' => 'Fournitures Bureau Import Export LLC',
            ],
            [
                'raison_sociale' => 'Agence Conseil Stratégie Business SA',
                'ice' => '005234567890001',
                'if' => 'IF99887766',
                'patente' => 'PA99887766',
                'rc' => 'RC99887',
                'adresse' => 'Tour Zénith, 10ème Étage, Rue Prince Moulay Abdellah',
                'ville' => 'Tanger',
                'telephone' => '+212664567890',
                'email' => 'contact@agence-conseil.ma',
                'representant' => 'Hassan El Moutassadeq',
                'domaine_activite' => 'Conseil et audit',
                'qualite_representant' => 'Associé-Fondateur',
                'cnss' => 'CNSS006789012',
                'banque' => 'BMCE Bank',
                'agence_bancaire' => 'Agence Port - Tanger',
                'rib' => '011410000000000005678901',
                'titulaire_compte' => 'Agence Conseil Stratégie Business SA',
            ],
            [
                'raison_sociale' => 'Travaux Électriques Moderne SARL',
                'ice' => '006234567890001',
                'if' => 'IF33445566',
                'patente' => 'PA33445566',
                'rc' => 'RC33445',
                'adresse' => 'Zone Industrielle El Jadida, Route 1, Hangar C',
                'ville' => 'El Jadida',
                'telephone' => '+212665678901',
                'email' => 'info@travaux-electriques.ma',
                'representant' => 'Rachid Alaoui',
                'domaine_activite' => 'Travaux électriques',
                'qualite_representant' => 'Chef de Projet',
                'cnss' => 'CNSS007890123',
                'banque' => 'Banque Salam',
                'agence_bancaire' => 'Agence Centre - El Jadida',
                'rib' => '011120000000000006789012',
                'titulaire_compte' => 'Travaux Électriques Moderne SARL',
            ],
            [
                'raison_sociale' => 'Nettoyage Professionnel Hygiène Plus LLC',
                'ice' => '007234567890001',
                'if' => 'IF77889900',
                'patente' => 'PA77889900',
                'rc' => 'RC77889',
                'adresse' => 'Rue 17, Secteur 13, Quartier Dar Es Salam',
                'ville' => 'Agadir',
                'telephone' => '+212666789012',
                'email' => 'commercial@hygieneplus.ma',
                'representant' => 'Nadia Bennani',
                'domaine_activite' => 'Nettoyage et hygiène',
                'qualite_representant' => 'Gérante',
                'cnss' => 'CNSS008901234',
                'banque' => 'Bank Al-Amal',
                'agence_bancaire' => 'Agence Agadir - Corniche',
                'rib' => '011970000000000007890123',
                'titulaire_compte' => 'Nettoyage Professionnel Hygiène Plus LLC',
            ],
            [
                'raison_sociale' => 'Conception Graphique Digital Créations SA',
                'ice' => '008234567890001',
                'if' => 'IF22334455',
                'patente' => 'PA22334455',
                'rc' => 'RC22334',
                'adresse' => 'Rue de l\'Innovation, Building A, Studio 201',
                'ville' => 'Casablanca',
                'telephone' => '+212667890123',
                'email' => 'studio@digitalcreations.ma',
                'representant' => 'Karim Ben Said',
                'domaine_activite' => 'Design et création graphique',
                'qualite_representant' => 'Directeur Créatif',
                'cnss' => 'CNSS009012345',
                'banque' => 'BOA Maroc',
                'agence_bancaire' => 'Agence Anfa - Casablanca',
                'rib' => '011010000000000008901234',
                'titulaire_compte' => 'Conception Graphique Digital Créations SA',
            ],
            [
                'raison_sociale' => 'Fournitures Médicales Pharma Care EURL',
                'ice' => '009234567890001',
                'if' => 'IF66778899',
                'patente' => 'PA66778899',
                'rc' => 'RC66778',
                'adresse' => 'Clinique Nouvelle, Rue Essaada, Bâtiment Médical',
                'ville' => 'Meknès',
                'telephone' => '+212668901234',
                'email' => 'medical@pharmacare.ma',
                'representant' => 'Dr. Samir Tazi',
                'domaine_activite' => 'Fournitures médicales',
                'qualite_representant' => 'Responsable Dentiste',
                'cnss' => 'CNSS010123456',
                'banque' => 'Crédit du Maroc',
                'agence_bancaire' => 'Agence Meknès Centre',
                'rib' => '011760000000000009012345',
                'titulaire_compte' => 'Fournitures Médicales Pharma Care EURL',
            ],
            [
                'raison_sociale' => 'Location Équipements Matériel Pro SARL',
                'ice' => '010234567890001',
                'if' => 'IF44556677',
                'patente' => 'PA44556677',
                'rc' => 'RC44556',
                'adresse' => 'Zone Portuaire, Quai 5, Warehouse 105',
                'ville' => 'Safi',
                'telephone' => '+212669012345',
                'email' => 'location@materielpro.ma',
                'representant' => 'Mustafa Ouinoune',
                'domaine_activite' => 'Location équipements',
                'qualite_representant' => 'Responsable Commercial',
                'cnss' => 'CNSS011234567',
                'banque' => 'Société Générale Maroc',
                'agence_bancaire' => 'Agence Safi',
                'rib' => '011250000000000010123456',
                'titulaire_compte' => 'Location Équipements Matériel Pro SARL',
            ],
            [
                'raison_sociale' => 'Restauration Collective Menu Gourmand LLC',
                'ice' => '011234567890001',
                'if' => 'IF88990011',
                'patente' => 'PA88990011',
                'rc' => 'RC88990',
                'adresse' => 'Avenue de la Marche Verte, Centre Restauration',
                'ville' => 'Kenitra',
                'telephone' => '+212670123456',
                'email' => 'service@menugourmand.ma',
                'representant' => 'Laila Bennani Fassi',
                'domaine_activite' => 'Restauration collective',
                'qualite_representant' => 'Chef de Cuisine',
                'cnss' => 'CNSS012345678',
                'banque' => 'Banque du Maroc',
                'agence_bancaire' => 'Agence Kenitra Nouvelle',
                'rib' => '011360000000000011234567',
                'titulaire_compte' => 'Restauration Collective Menu Gourmand LLC',
            ],
            [
                'raison_sociale' => 'Sécurité Surveillance Gardiennage Protec24 SA',
                'ice' => '012234567890001',
                'if' => 'IF55331122',
                'patente' => 'PA55331122',
                'rc' => 'RC55331',
                'adresse' => 'Boulevard de Koutoubia, Rue de sécurité, Bâtiment G',
                'ville' => 'Marrakech',
                'telephone' => '+212671234567',
                'email' => 'securite@protec24.ma',
                'representant' => 'Youssef Sabouni',
                'domaine_activite' => 'Sécurité et gardiennage',
                'qualite_representant' => 'Directeur Sécurité',
                'cnss' => 'CNSS013456789',
                'banque' => 'Crédit Agricole Maroc',
                'agence_bancaire' => 'Agence Gueliz - Marrakech',
                'rib' => '011540000000000012345678',
                'titulaire_compte' => 'Sécurité Surveillance Gardiennage Protec24 SA',
            ],
            [
                'raison_sociale' => 'Traduction Interprétation Pro-Languages EURL',
                'ice' => '013234567890001',
                'if' => 'IF99225544',
                'patente' => 'PA99225544',
                'rc' => 'RC99225',
                'adresse' => 'Rue de l\'Égalité, Appartement 305, Immeuble Business',
                'ville' => 'Rabat',
                'telephone' => '+212672345678',
                'email' => 'info@prologuages.ma',
                'representant' => 'Emma Fontaine Tazi',
                'domaine_activite' => 'Services de traduction',
                'qualite_representant' => 'Directrice Générale',
                'cnss' => 'CNSS014567890',
                'banque' => 'Attijariwafa Bank',
                'agence_bancaire' => 'Agence Ocean - Rabat',
                'rib' => '011930000000000013456789',
                'titulaire_compte' => 'Traduction Interprétation Pro-Languages EURL',
            ],
            [
                'raison_sociale' => 'Impression Emballage Matière Première Plus LLC',
                'ice' => '014234567890001',
                'if' => 'IF77334455',
                'patente' => 'PA77334455',
                'rc' => 'RC77334',
                'adresse' => 'Zone Industrielle Nord, Avenue Production, Usine 7',
                'ville' => 'Tantan',
                'telephone' => '+212673456789',
                'email' => 'production@matierepremiere.ma',
                'representant' => 'Abdelhamid Bennani',
                'domaine_activite' => 'Impression et emballage',
                'qualite_representant' => 'Directeur Production',
                'cnss' => 'CNSS015678901',
                'banque' => 'Banque Commerciale du Maroc',
                'agence_bancaire' => 'Agence Tantan',
                'rib' => '011410000000000014567890',
                'titulaire_compte' => 'Impression Emballage Matière Première Plus LLC',
            ],
            [
                'raison_sociale' => 'Formation Professionnelle Excellence EFP SA',
                'ice' => '015234567890001',
                'if' => 'IF88443366',
                'patente' => 'PA88443366',
                'rc' => 'RC88443',
                'adresse' => 'Complexe Éducatif, Route 3, Centre Formation',
                'ville' => 'Fez',
                'telephone' => '+212674567890',
                'email' => 'formation@efpexcellence.ma',
                'representant' => 'Dr. Abdennabi Alaoui Mdaghri',
                'domaine_activite' => 'Formation professionnelle',
                'qualite_representant' => 'Recteur',
                'cnss' => 'CNSS016789012',
                'banque' => 'Banque Atlantique Maroc',
                'agence_bancaire' => 'Agence Fez Nouvelle',
                'rib' => '011120000000000015678901',
                'titulaire_compte' => 'Formation Professionnelle Excellence EFP SA',
            ],
            [
                'raison_sociale' => 'Maintenance Industrielle Services Équipements Tech SARL',
                'ice' => '016234567890001',
                'if' => 'IF22114455',
                'patente' => 'PA22114455',
                'rc' => 'RC22114',
                'adresse' => 'Parc Technologique, Rue Innovation 2, Bâtiment H',
                'ville' => 'Salé',
                'telephone' => '+212675678901',
                'email' => 'maintenance@equiptech.ma',
                'representant' => 'Jamal Bennani Raji',
                'domaine_activite' => 'Maintenance industrielle',
                'qualite_representant' => 'Technicien en Chef',
                'cnss' => 'CNSS017890123',
                'banque' => 'BNP Paribas Maroc',
                'agence_bancaire' => 'Agence Salé Nouvelle Ville',
                'rib' => '011970000000000016789012',
                'titulaire_compte' => 'Maintenance Industrielle Services Équipements Tech SARL',
            ],
            [
                'raison_sociale' => 'Carrelage Peinture Revêtements BTP Création SA',
                'ice' => '017234567890001',
                'if' => 'IF44776699',
                'patente' => 'PA44776699',
                'rc' => 'RC44776',
                'adresse' => 'Marché Municipale, Rue Commerçants 21, Boutique 45',
                'ville' => 'Essaouira',
                'telephone' => '+212676789012',
                'email' => 'ventes@btpcreation.ma',
                'representant' => 'Sofiane Taib',
                'domaine_activite' => 'Matériaux BTP',
                'qualite_representant' => 'Vendeur',
                'cnss' => 'CNSS018901234',
                'banque' => 'Crédit Mutuel Maroc',
                'agence_bancaire' => 'Agence Essaouira-Port',
                'rib' => '011010000000000017890123',
                'titulaire_compte' => 'Carrelage Peinture Revêtements BTP Création SA',
            ],
            [
                'raison_sociale' => 'Mécanique Automobile Réparation Atelier 2000 LLC',
                'ice' => '018234567890001',
                'if' => 'IF66229911',
                'patente' => 'PA66229911',
                'rc' => 'RC66229',
                'adresse' => 'Boulevard du Garage, Atelier Mécanique 8',
                'ville' => 'Oujda',
                'telephone' => '+212677890123',
                'email' => 'repair@atelier2000.ma',
                'representant' => 'Abderrazak Mahjoubi',
                'domaine_activite' => 'Réparation automobile',
                'qualite_representant' => 'Mécanicien Chef',
                'cnss' => 'CNSS019012345',
                'banque' => 'Banque Marocaine pour l\'Afrique',
                'agence_bancaire' => 'Agence Oujda Centre',
                'rib' => '011760000000000018901234',
                'titulaire_compte' => 'Mécanique Automobile Réparation Atelier 2000 LLC',
            ],
            [
                'raison_sociale' => 'Paysagiste Horticulture Création Jardins Nature SA',
                'ice' => '019234567890001',
                'if' => 'IF33558899',
                'patente' => 'PA33558899',
                'rc' => 'RC33558',
                'adresse' => 'Boulevard de la Nature, Pépinière Centrale',
                'ville' => 'Fès-Meknès',
                'telephone' => '+212678901234',
                'email' => 'jardins@naturepaysagiste.ma',
                'representant' => 'Meryem Chouaib',
                'domaine_activite' => 'Paysagisme et horticulture',
                'qualite_representant' => 'Chef Paysagiste',
                'cnss' => 'CNSS020123456',
                'banque' => 'Société Générale Maroc',
                'agence_bancaire' => 'Agence Meknes Zone Nouvelle',
                'rib' => '011250000000000019012345',
                'titulaire_compte' => 'Paysagiste Horticulture Création Jardins Nature SA',
            ],
        ];

        foreach ($fournisseurs as $data) {
            Fournisseur::create($data);
        }
    }
}
