<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LigneBudgetaire;

class LigneBudgetaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lignes = [
            // ==========================================
            // 1. INVESTISSEMENT (INV)
            // ==========================================
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '415',
                'article' => '415',
                'paragraphe' => null,
                'ligne' => null,
                'intitule' => 'DEVELOPPMENT DES FILIERES DE PRODUCTION',
                'niveau' => 'rubrique',
                'parent_code' => null,
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41510',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => null,
                'intitule' => 'MISE A NIVEAU DES INFRASTRUCTURES',
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151010',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '10',
                'intitule' => 'Construction des bâtiments administratifs',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151013',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '13',
                'intitule' => "Travaux d'aménagement des batiments administratifs et d'installation de matériels divers",
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151014',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '14',
                'intitule' => 'Entretien et réparation des bâtiments administratifs',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151015',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '15',
                'intitule' => 'Etudes et controles',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151017',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '17',
                'intitule' => "Achat et installation d'enseignes",
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151020',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '20',
                'intitule' => 'Matériél et équipement',
                'niveau' => 'paragraphe',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151021',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '21',
                'intitule' => 'Achat de matériél et mobilier de bureau',
                'niveau' => 'ligne',
                'parent_code' => '4151020',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151022',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '22',
                'intitule' => 'Achat de matériel Technique et de Démonstration',
                'niveau' => 'ligne',
                'parent_code' => '4151020',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151025',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '25',
                'intitule' => 'Achat de matériél informatique, de logiciels et de progiciels',
                'niveau' => 'ligne',
                'parent_code' => '4151020',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151030',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '30',
                'intitule' => 'Achat de biens et de services',
                'niveau' => 'paragraphe',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151031',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '31',
                'intitule' => "Fournitures de bureau, produits d'impression, papeterie et imprimés",
                'niveau' => 'ligne',
                'parent_code' => '4151030',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4151033',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '33',
                'intitule' => 'Achat de fournitures techniques, informatiques et audio-visuelles',
                'niveau' => 'ligne',
                'parent_code' => '4151030',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41520',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => null,
                'intitule' => 'DEVELOPPEMENT DU CONSEIL AGRICOLE',
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152010',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '10',
                'intitule' => 'Renforcement du Conseil Agricole Public',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152011',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '11',
                'intitule' => "Frais d'organisation et de participation aux manifestations aux évenements et foires agricoles",
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152012',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '12',
                'intitule' => "Frais d'organisation et de participation aux journées de sensibilisation, de formation,d'information et de conseil agricole",
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152013',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '13',
                'intitule' => 'Essais de démonstration et achat des intrants pour FFS',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152014',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '14',
                'intitule' => 'Frais de voyage des agriculteurs et techniciens',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152016',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '16',
                'intitule' => 'Frais de formation et de visite',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152019',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '19',
                'intitule' => 'Hebergement, hotellerie et restauration',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152020',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '20',
                'intitule' => 'Renforcement des capacités des conseillers agricoles publics',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152018',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '18',
                'intitule' => 'Frais d\'organisation des sessions de création des coopératives',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152021',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '21',
                'intitule' => 'Frais de Prise en Charge et de Formation des Conseillers et Responsables du Conseil Agricole',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152022',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '22',
                'intitule' => "Frais de Formation, d'Accompagnement et de Voyage Prise des Conseillers Agricoles et Assistance Technique dans le Cadre du Projet de Conseil de Gestion",
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152023',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '23',
                'intitule' => 'Hébergement, Restauration et Frais de Réception',
                'niveau' => 'ligne',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152030',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '30',
                'intitule' => 'Communication et information',
                'niveau' => 'paragraphe',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152035',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '35',
                'intitule' => "Frais d'organisation de compagne de communication et production des articles promotionnels",
                'niveau' => 'ligne',
                'parent_code' => '4152030',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152040',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '40',
                'intitule' => 'Conseil agricole privé',
                'niveau' => 'paragraphe',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152042',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '42',
                'intitule' => 'Assistance Technique encadrement et accompagnement par le Conseil Privé',
                'niveau' => 'ligne',
                'parent_code' => '4152040',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152050',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '50',
                'intitule' => 'Nettoyage des Touffes',
                'niveau' => 'paragraphe',
                'parent_code' => '41520',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152051',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '51',
                'intitule' => 'Achat de matériel de démonstration',
                'niveau' => 'ligne',
                'parent_code' => '4152050',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152052',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '52',
                'intitule' => 'Frais de Formation et de Visite',
                'niveau' => 'ligne',
                'parent_code' => '4152050',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152053',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '53',
                'intitule' => "Frais d'organisation et de participation aux journées de sensibilisation, de formation,d'information et de conseil agricole",
                'niveau' => 'ligne',
                'parent_code' => '4152050',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4152054',
                'article' => '415',
                'paragraphe' => '20',
                'ligne' => '54',
                'intitule' => 'Hébergement, Hotellerie et Restauration',
                'niveau' => 'ligne',
                'parent_code' => '4152050',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41530',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => null,
                'intitule' => 'PROJET DE DEVELOPPEMENT SOCIO-ECONOMIQUE DE LA FEMME RURALE',
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153010',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '10',
                'intitule' => 'Frais de formation et de prise en charge des femmes rurales',
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153020',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '20',
                'intitule' => "Voyage d'étude des femmes rurales",
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153030',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '30',
                'intitule' => "Essais de démonstration Et achat d'intrants agricoles",
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153040',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '40',
                'intitule' => "Achat d'animaux d'élevage et de ruches",
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153050',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '50',
                'intitule' => "Achat matériel d'élevage",
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153060',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '60',
                'intitule' => 'Achat de matériel de démonstration',
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4153070',
                'article' => '415',
                'paragraphe' => '30',
                'ligne' => '70',
                'intitule' => 'Achat de matériel de valorisation des produits agricoles',
                'niveau' => 'ligne',
                'parent_code' => '41530',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41540',
                'article' => '415',
                'paragraphe' => '40',
                'ligne' => null,
                'intitule' => 'PROJET SAFRAN-DATTES (COOPERATION BELGE)',
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41542',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => null,
                'intitule' => 'Développement et valorisation du Safran',
                'niveau' => 'projet',
                'parent_code' => '41540',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154210',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '10',
                'intitule' => 'Coopération et partenariat',
                'niveau' => 'paragraphe',
                'parent_code' => '41542',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154211',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '11',
                'intitule' => 'Renforcement, Accompagnement et encadrement des producteurs et des organisations professionalles',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154212',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '12',
                'intitule' => 'Appui à la production et suivi environnemental',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154213',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '13',
                'intitule' => 'Professionalisation de la collecte et des aspects post-récolte',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154215',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '15',
                'intitule' => 'Elaboration et implémentation de la stratégie de commercialisation',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154216',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '16',
                'intitule' => 'Renforcement, Accompagnement et encadrement des coopératives et GIEs',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154217',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '17',
                'intitule' => "Appui au fonctionnement de l'interprofession",
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4154218',
                'article' => '415',
                'paragraphe' => '42',
                'ligne' => '18',
                'intitule' => 'Frais de communication et de promotion',
                'niveau' => 'ligne',
                'parent_code' => '4154210',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41550',
                'article' => '415',
                'paragraphe' => '50',
                'ligne' => null,
                'intitule' => 'PROJET PAGIE POUR LE DEVELOPPEMENT DE LA FILIERE PHOENICICOLE',
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4155010',
                'article' => '415',
                'paragraphe' => '50',
                'ligne' => '10',
                'intitule' => "Frais d'Encadrement et d'Accompagnement",
                'niveau' => 'ligne',
                'parent_code' => '41550',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4155030',
                'article' => '415',
                'paragraphe' => '50',
                'ligne' => '30',
                'intitule' => 'Appui à l\'alphabétisation fonctionnelle et organisation des femmes et des jeunes en coopératives de services',
                'niveau' => 'ligne',
                'parent_code' => '41550',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '41570',
                'article' => '415',
                'paragraphe' => '70',
                'ligne' => null,
                'intitule' => "Projet d'accompagnement a l'opération de Mélkisation des terres collectives",
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Investissement',
                'code_imputation' => '4157010',
                'article' => '415',
                'paragraphe' => '70',
                'ligne' => '10',
                'intitule' => 'Contribution aux projets de partenariat',
                'niveau' => 'ligne',
                'parent_code' => '41570',
            ],

            // ==========================================
            // 2. FONCTIONNEMENT (FONCT)
            // ==========================================
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '415',
                'article' => '415',
                'paragraphe' => null,
                'ligne' => null,
                'intitule' => 'DEVELOPPMENT DES FILIERES DE PRODUCTION',
                'niveau' => 'rubrique',
                'parent_code' => null,
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '41510',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => null,
                'intitule' => "ACTIONS D'APPUI",
                'niveau' => 'projet',
                'parent_code' => '415',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151010',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '10',
                'intitule' => 'Charges immobilières',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151012',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '12',
                'intitule' => 'Frais de sécurité, de surveillance et de gardiennage',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151013',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '13',
                'intitule' => 'Jardinage et néttoyage',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151030',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '30',
                'intitule' => 'Transport et Déplacement',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151033',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '33',
                'intitule' => 'Indemnités de Déplacement et changement de résidence à l\'interieur du Royaume',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151040',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '40',
                'intitule' => 'Achat de biens et services',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151042',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '42',
                'intitule' => 'Achat de fournitures de bureau',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151060',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '60',
                'intitule' => 'Etude,conseil, formation, assistance et services assimilés',
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
            [
                'type_budget' => 'Fonctionnement',
                'code_imputation' => '4151061',
                'article' => '415',
                'paragraphe' => '10',
                'ligne' => '61',
                'intitule' => "Frais de justice et honoraires d'avocats",
                'niveau' => 'ligne',
                'parent_code' => '41510',
            ],
        ];

        LigneBudgetaire::query()->delete();

        foreach ($lignes as $data) {
            LigneBudgetaire::create($data);
        }
    }
}
